services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.11.16@sha256:6fbacaa2db3851ecb4234f74e14d8a072298e15922a3af976fcc03ae834d9d73
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
