services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.13.0@sha256:48b2bba124a4604992a1e549a656ff7338a2ef93dbe80c358798602c1c94afa7
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
