services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.15.0@sha256:c258debb6cd0e2be844adad8231a1268d9e12fa46aa0f78e15472bbe7837f12b
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
