services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.14.0@sha256:72628a43fbd8574b066cd06273545ec9cc74314f360598ee8de27770bd904faa
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
