services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.17.0@sha256:64aa6aed2b94317475019a2cde883ac4f6d67e4b5fbdf9bea5ff229cc9583f5a
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
