services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.16.0@sha256:3006944a3b1f37d36be5a982eb8c8b3b1448a9c82699226532b6630f21fa637c
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
