services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.11.17@sha256:15b963783b3dc24a6256ebc1bffd4fc6c133348810faf86ecaa939912fd311b6
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
