services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.12.0@sha256:205bfb9b4907c9acac5b99a407ad5fc4bf528a73dc735fa39ffc2c3a9335cbe9
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"
